messages:
  setup:
    Buy: Nastavil jsi !items for sale at a price of !price!
    Sell: You have put a bounty of !price for !items!
    Donate: You have setup a donation box for !items!
    DonateHand: You have setup a donation box for all item types
    Slot: You have setup a !price slot machine offering !items!
    iBuy: You have put !items infinitely for sale at a price of !price!
    iSell: You have put an infinite bounty of !price for !items!
    gBuy: You have setup a ghost shop selling !items for !price! (Note, you will not receive or lose money from this shop)
    gSell: You have setup a ghost shop buying !items for !price! (Note, you will not receive or lose money from this shop)
    Day: You have setup a time controller that costs !price!
    Night: You have setup a time controller that costs !price!
    Rain: You have setup a weather controller that costs !price!
    ClearSkies: Nastavil jsi ovladac pocasi za !price!
    DeviceOn: Vytvoril jsi zapinac pristroje za !price!
    DeviceOff: Vytvoril jsi vypinac pristroje za !price!
    Toggle: You have setup a device toggler that costs !price!
    Device: Nastavil jsi docasny ovladac zarizeni za !price!
    Heal: You have setup a healing station that costs !price!
    Repair: You have setup a repair station that costs !price!
    Dispose: You have setup a dispose sign
    DeviceItem: You have setup a device temporary activator that costs !items!
    iSlot: You have setup a !price slot machine offering infinite !items!
    Enchant: You have setup an Enchanter that costs !price and enchants with !enchantments!
    iSellXP: You have put a bounty of !price for !xp XP
    iBuyXP: You have put !xp XP for sale at a price of !price!
    iTrade: Nastavil jsi neomezeny vymenny obchod. Chces !chest1 - nabizis !chest2!
    Trade: Nastavil jsi vymenny obchod. Chces !chest1 - nabizis !chest2!
    TpToOwner: You have setup a command example shop, selling teleports to !owner for !price!
    Class: You have setup a shop to sell a class of items for !price!
    Disenchant: You have setup a sign that removes enchantments for !price!
    Command: You have created a sign that runs commands for !price!
    Jukebox: You have set up a Jukebox that plays records from the chest for !price!
    Kit: You have setup a one time use kit (!items) for !price!
    ResetKit: You have setup a sign that resets !param signs!
    iXPBuy: You have put !items for sale at the cost of !xp XP points!
    iXPSell: You have put !items infinitely for sale at a price of !xp XP points!
    uVymena: Nastavil jsi neomezeny vymenny obchod. Chces !chest1 - nabizis !chest2!
    Vymena: Nastavil jsi vymenny obchod. Chces !chest1 - nabizis !chest2!
    DeviceToggle: Vytvoril jsi prepinac pristroje za !price!
    Koupit: Dal jsi !items na prodej za !price!
    Prodat: Vykupujes !items za !price!
    Darovat: Otevrel jsi verejnou sbirku na !items!
    uKoupit: Nyni prodavas nekonecne zasoby !items za !price!
    uProdat: Nyni vykupujes !items za !price do svych nekonecnych zasob!
    gKoupit: Nastavil jsi nezavisly prodej !items za !price! (V tomto obchode neziskas ani neztratis zadne penize)
    gProdat: Nastavil jsi nezavisly vykup !items za !price! (V tomto obchode neziskas ani neztratis zadne penize)
    Den: You have setup a time controller that costs !price!
    Noc: Nastavil jsi ovladac casu za !price!
    Zdravi: Vytvoril jsi lekarskou pohotovost za !price!
    Opravit: Vytvoril jsi opravnu za !price!
    Odevzdat: Vytvoril jsi darovaci bednu!
    Dest: Nastavil jsi ovladac pocasi za !price!
    Kos: Vytvoril jsi kos.
  confirm:
    Buy: Buy !items for !price?
    Sell: Sell !items for !price?
    Donate: Donate !items?
    DonateHand: Donate !items?
    Slot: Chces si zahrat za !price? Klepni pravym tlacitkem!
    iBuy: Buy !items for !price?
    iSell: Sell !items for !price?
    gBuy: Buy !items for !price?
    gSell: Sell !items for !price?
    Day: Set the time to day for !price?
    Night: Set the time to night for !price?
    Rain: Set the weather to raining for !price?
    ClearSkies: Set the weather to clear skies for !price?
    DeviceOn: Chces zapnout tento pristroj za !price?  Klepni pravym tlacitkem!
    DeviceOff: Chces vypnout tento pristroj za !price? Klepni pravym tlacitkem!
    Toggle: Toggle this device for !price?
    Device: Chces docasne zapnout tento pristroj za !price? Klepni pravym tlacitkem!
    Heal: Heal yourself for !price?
    Repair: Repair the item held in your hand for !price?
    Dispose: Dispose of !items?
    DeviceItem: Temporarily activate this device for !items?
    iSlot: Play this infinitely stocked slot machine for !price?
    Enchant: Enchant your item with !enchantments for !price?
    iSellXP: Sell !xp XP for !price?
    iBuyXP: Buy !xp XP for !price?
    iTrade: Chces koupit !chest2 za !chest1? Klepni pravym tlacitkem!
    Trade: Chces koupit !chest2 za !chest1? Klepni pravym tlacitkem!
    TpToOwner: Teleport to !owner for !price?
    Class: Buy the class containing !items for !price?
    Disenchant: Remove enchantments on the item in your hand for !price?
    Command: Run the commands on this sign for !price?
    Jukebox: Play a record for !price?
    Kit: Get this kit (!items) one time for !price?
    ResetKit: Reset your !param signs for !price!
    iXPBuy: Buy !items for !xp XP points?
    iXPSell: Sell !items for !xp XP points?
    Redstone: Zapnout pristroj za !price?
    uVymena: Chces koupit !chest2 za !chest1? Klepni pravym tlacitkem!
    Vymena: Chces koupit !chest2 za !chest1? Klepni pravym tlacitkem!
    DeviceToggle: Chces prepnout tento pristroj za !price? Klepni pravym tlacitkem!
    Koupit: Chces koupit !items za !price? Klepni pravym tlacitkem!
    Prodat: Chces prodat !items za !price? Klepni pravym tlacitkem!
    Darovat: Chces darovat !items? Klepni pravym tlacitkem!
    Odevzdat: Chces darovat !items? Klepni pravym tlacitkem!
    uKoupit: Chces koupit !items za !price? Klepni pravym tlacitkem!
    uProdat: Chces prodat !items za !price? Klepni pravym tlacitkem!
    gKoupit: Chces koupit !items za !price? Klepni pravym tlacitkem!
    gProdat: Chces prodat !items za !price? Klepni pravym tlacitkem!
    Den: Chces nastavit den za !price? Klepni pravym tlacitkem!
    Noc: Chces nastavit noc za !price? Klepni pravym tlacitkem!
    Dest: Chces vyjasnit oblohu za !price? Klepni pravym tlacitkem!
    Zdravi: Chces se vylecit za !price? Klepni pravym tlacitkem!
    Opravit: Chces opravit to co drzis v ruce za !price? Klepni pravym tlacitkem!
    Kos: Chces vyhodit !items drzici v ruce? Klepni pravym tlacitkem!
  transaction:
    Buy: You have bought !items for !price!
    Sell: You have sold !items for !price!
    Donate: You have donated !items!
    DonateHand: You have donated !items!
    Slot: Vyhral jsi !items!
    iBuy: You have bought !items for !price!
    iSell: You have sold !items for !price!
    gBuy: You have bought !items for !price!
    gSell: You have sold !items for !price!
    Day: You set the time to day for !price!
    Night: You set the time to night for !price!
    Rain: You set the weather to raining for !price!
    ClearSkies: You set the weather to clear skies for !price!
    DeviceOn: You activated this device for !price!
    DeviceOff: You deactivated this !price!
    Toggle: You toggled this device for !price!
    Device: You temporarily activated this device for !price!
    Heal: You healed yourself for !price!
    Repair: You repaired an item for !price!
    Dispose: You have disposed of !items!
    DeviceItem: You temporarily activated this device for !items!
    iSlot: You won !items!
    Enchant: Enchanted your item with !enchantments for !price!
    iSellXP: Sold !xp XP for !price!
    iBuyXP: Added !xp XP for !price!
    iTrade: Vymenil jsi !chest1 za !chest2!
    Trade: Vymenil jsi !chest1 za !chest2!
    TpToOwner: You teleported to !owner for !price!
    Class: You bought the class containing !items for !price!
    Disenchant: You removed the enchantments on the item in your hand for !price!
    Command: You run the commands in the sign for !price!
    Jukebox: You've made the Jukebox play a record for !price!
    Kit: You acquired !items for !price!
    ResetKit: You reset !param signs for !price!
    iXPBuy: You have bought !items for !xp XP points!
    iXPSell: You have sold !items for !xp XP points!
    Redstone: Device activated for !price!
    uVymena: Vymenil jsi !chest1 za !chest2!
    Vymena: Vymenil jsi !chest1 za !chest2!
    DeviceToggle: You toggled this device for !price!
    Koupit: Prave jsi koupil !items za !price!
    Prodat: Prodal jsi !items za !price!
    Darovat: Daroval jsi !items!
    Odevzdat: Daroval jsi !items!
    uKoupit: Prave jsi koupil !items za !price!!
    uProdat: Prodal jsi !items za !price!
    iKoupit: Prave jsi koupil !items za !price!!
    iProdat: Prodal jsi !items za !price!
    gKoupit: You have bought !items for !price!
    gProdat: Prodal jsi !items za !price!
    Den: Nastavil jsi den za !price!
    Noc: Nastavil jsi noc za !price!
    Dest: You set the weather to raining for !price!
    Zdravi: You healed yourself for !price!
    Opravit: You repaired an item for !price!
    Kos: You have disposed of !items!
  transaction_owner:
    Buy: \!customer koupil !items for !price from you!
    Sell: \!customer sold you !items for !price!
    Donate: \!customer donated !items to you!
    DonateHand: \!customer donated !items to you!
    Slot: \!customer played a slot machine for !price and won !items!
    iBuy: \!customer bought !items for !price from your infinite store!
    iSell: \!customer sold !items to your infinite store!
    gBuy: \!customer bought !items from your ghost store!
    gSell: \!customer sold !items to your ghost store!
    Day: \!customer set the time to day for !price!
    Night: \!customer set the time to night for !price!
    Rain: \!customer set the weather to raining for !price!
    ClearSkies: \!customer vycistil oblohu za !price!
    DeviceOn: \!customer aktivoval zarizeni za !price!
    DeviceOff: \!customer deaktivoval zarizeni !price!
    Toggle: \!customer toggled your device for !price!
    Device: \!customer temporarily activated your device for !price!
    Heal: \!customer healed at your station for !price!
    Repair: \!customer repaired an item at your station for !price!
    Dispose: \!customer disposed of !items!
    DeviceItem: \!customer temporarily activated your device for !items!
    iSlot: ''
    Enchant: \!customer enchanted his item with !enchantments for !price!
    iSellXP: ''
    iBuyXP: ''
    iTrade: ''
    Trade: \!customer vymenil !chest1 za tvych !chest2!
    TpToOwner: \!customer teleported to you for !price!
    Class: ''
    Disenchant: ''
    Command: ''
    Jukebox: \!customer played a record on your jukebox for !price!
    Kit: ''
    ResetKit: ''
    iXPBuy: ''
    iXPSell: ''
    Redstone: \!customer activated your redstone device for !price!
    uVymena: ''
    Vymena: \!customer vymenil !chest1 za tvych !chest2!
    DeviceToggle: \!customer prepnul zarizeni za !price!
    Koupit: \!customer si od tebe koupil !items za !price!
    Prodat: \!customer ti prodal !items za !price!
    Darovat: \!customer ti daroval !items!
    Odevzdat: \!customer ti daroval !items!
    uKoupit: ''
    uProdat: ''
    gKoupit: \!customer si od tebe koupil !items za !price!
    gProdat: \!customer ti prodal !items za !price!
    Den: \!customer nastavil den za !price!
    Noc: \!customer nastavil noc za !price!
    Dest: \!customer nastavil destive pocasi za !price!
    Zdravi: \!customer se vylecil za !price!
    Opravit: \!customer opravil sve nastroje za !price!
    Kos: ''
errors:
  no_permission: Nemas pravo vytvaret obchodni cedulky!
  no_permission_use: Nemas pravo tyto obchodni cedulky pouzivat!
  no_permission_changeowner: Kzmene majitele tohoto obchodu nemas prava!
  invalid_operation: Cedulka kterou jsi oznacil neni platna!
  chest_empty: Obchod je prazdny!
  chest_missing: Pro tento typ obchodu musis predem oznacit nejakou bednu!
  lever_missing: Pro tento typ obchodu musis predem oznacit nejakou paku!
  no_player_money: Nemas !price pro zaplaceni!
  no_shop_money: Obchod nema !price aby ti zaplatil!
  out_of_business: This shop appears to have gone out of business!
  out_of_stock: V tomto obchode dosel material!
  overstocked: Tento obchod je jiz plny!
  player_doesnt_have_items: Nemas dostatek predmetu na prodej! (!items)
  no_item_in_hand: Musis v ruce drzet nejaky predmet!
  player_overstocked: Mas plny inventar!
  sign_location_stored: Pozice cedulky byla ulozena, nyni oznac nejakou truhlu!
  made_day: '!player prepnul na den!'
  made_night: '!player prepnul na noc!'
  made_rain: '!player prepnul na destive pocasi!'
  made_clear_skies: '!player vycistil oblohu!'
  already_on: Zarizeni je jiz zapnuto
  already_off: Zarizeni je jiz vypnuto
  link_notallowed: Nemas pravo oznacit tuto bednu.
  item_already_repair: Nastroj je jiz opraven!
  already_raining: Jiz je destive pocasi!
  already_clear_skies: Jiz neprsi!
  already_full_health: Jiz jsi uzdraveny!
  saving: Ukladani obchodu
  saved: Obchody uspesne ulozeny!
  shop_removed: Odstranen neplatny obchod.
  invalid_item_to_repair: Tento predmet nemuze byt opraven!
  no_item_to_repair: V ruce musis mit platny nastroj pro opraveni!
  backup_fail: Zaloha vsech obchodu skoncila neuspesne!
  too_far: Maximalni vzdalenost mezi cedulkou a bednami je !max.
  too_many_shops: Dosahl jsi maximalniho poctu obchodu, maximum je !max. Pokud chces dalsi obchody, porid si VIP.
  enchanted_not_allowed: Nemas pravo opravovat si enchantovane predmety.
  enchantment_missing: At least one enchanted item is needed, please put one in the chest(s)!
  item_not_enchantable: The item in your hand is not enchantable!
  no_player_xp: Nemas dostatek XP pro prodej (!xp)!
  no_item_to_disenchant: You need to be holding the item you want to disenchant!
  nothing_to_disenchant: That item can not be disenchanted!
  multiworld_not_allowed: Obchody mezi svety nejsou povoleny!
  no_permit_owner: Majitel obchodu jiz nadale nema prava ho udrzovat!
  need_permit: Pro tento obchod musis mit urcita vyssi prava!
  villager_trading_disabled: Vymenovani s villagery neni dovoleno jinde, nez na /sb v SHOPu.
  not_allowed_to_link_sharesigns: You are not allowed to link Share signs to this shop!
  no_shop_linked_to_sharesign: This Share sign has not been linked to any shops.
  share_sign_splits_profit: This Share sign splits profits between !profits for the Shop(s) at !profitshops
  registered_share_sign: Registered a Share sign, please click the Shop sign next.
  unlinked_share_sign: Unlinked Share sign from Shop.
  linked_share_sign: Succesfully linked Share sign to Shop.
  not_allowed_to_link_restrictedsigns: You are not allowed to link Restricted signs to this shop!
  no_shop_linked_to_restrictedsign: This Restricted sign has not been linked to any shops.
  registered_restricted_sign: Registered a Restricted sign, please click the Shop sign next.
  unlinked_restricted_sign: Unlinked Restricted sign from Shop.
  linked_restricted_sign: Succesfully linked Restricted sign to Shop.
  restricted_sign_restricts: This Restricted sign restricts use of the Shop(s) at !restrictedshops
  towny_insufficient_funds: Insufficient funds in shop account!
  towny_owner_not_mayor_or_assistant: The shop owner isn't a mayor or assistant of a town.
  towny_owner_not_belong_to_town: The shop owner likely doesn't belong to a town.
  towny_bank_withdrawls_not_allowed: The current Towny setup does not allow bank withdrawls!
  restricted_from_using: Tento obchod nemuzes pouzivat!
  restricted_but_owner: Tento obchod nemuzes pouzivat protoze jsi majitelem.
  item_on_blacklist: The item !blacklisted_item is on the blacklist and can not be used with Shops.
  item_on_blacklist_but_op: The item !blacklisted_item is on the blacklist but you're OP.
  block_is_protected: Tento blok je chranen, nemuzes s nim jakkoli manipulovat.
  updated_shop: Obchod byl aktualizovan podle noveho obsahu bedny (beden).
  failed_to_update_shop: Obchod nebyl aktualizovan.
  price_drawn_from_essentials: Please note that the price was drawn from Essentials and is thus variable.
  only_one_time: Tento obchod muzes pouzit pouze jednou.
  nothing_to_reset_ontime: You are already allowed to use !param signs one time. So there's nothing to reset.
  shop_on_cooldown: Tento obchod nemuzes pouzivat tak casto, vydrz jeste !cooldownleft seconds.
  damaged_items_shop_homogeneous: A shop accepting damaged items can only deal in one type of item! Damaged items are not accepted until the shop is fixed.
  use_item_to_destroy_shop: Tento obchod je chranen a muze byt znicen pouze !destroymaterial.
  no_items_defined_for_shop: Pro tento obchod nejsou nastaveny zadne veci. Nahlas majitelovi.
  notifications_shop_built: \!player just created a(n) !signtype sign at (!x, !y, !z)